version: '3.8'

services:

  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: order
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass

  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"

  service-build:
    build:
      context: .
      dockerfile: build/dockerfile
    image: order_service:latest

  order_service:
    image: order_service:latest
    ports:  
      - 8080:8080
    environment:
      - DATABASES.HOST=postgres
      - MONGO.URL=mongodb://mongo:27017
    depends_on:
      - postgres
      - mongo
    restart: always