version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: order
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass

  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"

