// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/order-service/api/v1/patients": {
            "get": {
                "summary": "list patinets",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HttpError"
                        }
                    }
                }
            }
        },
        "/order-service/api/v1/patients/{patientId}/orders": {
            "get": {
                "summary": "list patinet's order",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "patinet ID",
                        "name": "patientId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HttpError"
                        }
                    }
                }
            },
            "post": {
                "summary": "create patinet's order",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "patinet ID",
                        "name": "patientId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "order",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Order"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HttpError"
                        }
                    }
                }
            }
        },
        "/order-service/api/v1/patients/{patientId}/orders/{orderId}": {
            "put": {
                "summary": "update patinet's order",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "patinet ID",
                        "name": "patientId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "order ID",
                        "name": "orderId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "order",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Order"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HttpError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "code.Code": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                16,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15
            ],
            "x-enum-varnames": [
                "Code_OK",
                "Code_CANCELLED",
                "Code_UNKNOWN",
                "Code_INVALID_ARGUMENT",
                "Code_DEADLINE_EXCEEDED",
                "Code_NOT_FOUND",
                "Code_ALREADY_EXISTS",
                "Code_PERMISSION_DENIED",
                "Code_UNAUTHENTICATED",
                "Code_RESOURCE_EXHAUSTED",
                "Code_FAILED_PRECONDITION",
                "Code_ABORTED",
                "Code_OUT_OF_RANGE",
                "Code_UNIMPLEMENTED",
                "Code_INTERNAL",
                "Code_UNAVAILABLE",
                "Code_DATA_LOSS"
            ]
        },
        "models.ErrorDetails": {
            "type": "object",
            "required": [
                "error_msg",
                "row"
            ],
            "properties": {
                "error_msg": {
                    "type": "string"
                },
                "row": {}
            }
        },
        "models.HttpError": {
            "type": "object",
            "required": [
                "code",
                "error",
                "message"
            ],
            "properties": {
                "code": {
                    "$ref": "#/definitions/code.Code"
                },
                "error": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ErrorDetails"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.Order": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "doctor_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "patient_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/code.Code"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Order Upload API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
